name = "eight-template"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "bun run prisma generate"
dev = "bun run prisma migrate deploy && bun run dev:start"
